#!/bin/sh

source functions

month=`date +%b%Y`
today=`date +%b%d%y`

download_crossword() {
	#downloads today's nyt crossword
	local today=$1
	local crossword_url="http://www.nytimes.com/svc/crosswords/v2/puzzle/print/$today.pdf"
	local nyt_cookies=`cat $source_locations/nyt-cookies.txt`

	new_uuid crossword_uuid

	wget $crossword_url \
		--header="Referer: https://www.nytimes.com/crosswords/archive/daily" \
		--header="Cookie: $nyt_cookies" \
		-O "$xochitl_loc/$crossword_uuid.pdf"

	rm_mkdir "/Crosswords/$month"
	local month_dir
	find_uuid $month "dir" month_dir_uuid

	create_doc_metadata $crossword_uuid $month_dir_uuid $today $xochitl_loc
	create_doc_content $crossword_uuid $xochitl_loc
}

find_uuid $today "doc" crossword_uuid
if [[ $crossword_uuid == "" ]]; then
	download_crossword $today
	systemctl restart xochitl.service
else
	exit 0
fi
