#!/bin/sh

source ./env
source ./remarkable-file-functions/functions

# Prints usage message
function print_help() {
	echo -e "Usage: rm-sync-pdf [OPTIONS]\n\tMandatory Options:\n\t\t-u: \t URL to pull pdf from.\n\t\t-n:\tName to give the downloaded pdf.\n\tOptional Options:\n\t\t-c:\tLocation of a cookie file. Necessary if authentication is required for the pdf.\n\t\t-d:\tDirectory on the remarkable to store the file under.\n\t\t\tIf any of the directories in the path don't exist they will be created.\n\t\t-h\tPrints this usage message and exits."
	exit 2
}

download_pdf() {
	#downloads the pdf requested by the -u flag

	local pdf_uuid=$(new_uuid)

	if [[ -z ${WGET} ]]; then
		WGET=$(which wget)
	fi

	if [[ -z ${cookie_file} ]]; then
		$WGET \
		-O "$xochitl_loc/$pdf_uuid.pdf" \
		$url
	else
		$WGET \
		--load-cookies $cookie_file \
		-O "$xochitl_loc/$pdf_uuid.pdf" \
		$url

	fi


	local wget_exit=$?
    echo "wget exit status: $wget_exit"

	if [[ $wget_exit != "0" ]]; then
		exit "$wget_exit"
	fi

	if [[ $dir ]]; then
		local dir_uuid=$(rm_mkdir "$dir")
	fi

	create_doc_metadata "$pdf_uuid" "$dir_uuid" "$name" "$xochitl_loc"
	create_doc_content "$pdf_uuid" "1" "$xochitl_loc"
}

restart=false

while getopts 'u:c:n:d:hr' flag; do
	case "${flag}" in
		u)
			url="${OPTARG}" ;;
		c)
			cookie_file="${OPTARG}" ;;
		d)
			dir="${OPTARG}" ;;
		n)
			name="${OPTARG}" ;;
		h)
			print_help ;;
        r)
            restart=true ;;
		*)
			echo "$1 is not an option"
			print_help ;;
	esac
done

if [[ $url == "" ]]; then
	print_help
fi

if [[ $name ]]; then
	find_uuid $name "DocumentType" pdf_uuid
fi

if [[ $cookie_file ]]; then
	cookies=`cat $cookie_file`
fi

if [[ $pdf_uuid == "" ]]; then
	echo "Downloading file"
	download_pdf
    if [[ $restart = true ]]; then
	    systemctl restart xochitl.service
    fi
else
	exit 0
fi
